In [1]:
from splinter import Browser

from bs4 import BeautifulSoup
import os
import pandas as pd

executable_path = {'executable_path': 'chromedriver.exe'}

browser = Browser('chrome', **executable_path, headless=False)

# from splinter import browser

browser.visit('https://www.fec.gov/data/receipts/individual-contributions/?data_type=processed&committee_id=C00334037&committee_id=C00693234&committee_id=C00696948&committee_id=C00697441&committee_id=C00699090&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020')

button = browser.find_by_css("#main > section > div.data-container > div.data-container__widgets.js-data-widgets > div.data-container__head > div > div.data-container__export > button")

# button = browser.find_by_css("#main > section > div.data-container > div.data-container__widgets.js-data-widgets > div.data-container__head > div > div.data-container__export > button")

button.click()

browser.find_by_css("body > div.downloads > div > ul > li > div > a").click()



files = os.listdir("C:/Users/shorv/Downloads")

path = "C:/Users/shorv/Downloads/"

file_locations = []

for f in files:

    if 'schedule' in f:

        newfile = path + f

        file_locations.append(newfile)

frames = {}

for file in file_locations:

    name = file[-23:]

    frames[name] = pd.read_csv(file)

In [7]:
new = file_locations[2]
df = pd.read_csv(new, converters={'contributor_zip': str})
df.head()

,committee_id,committee_name,report_year,report_type,image_number,line_number,transaction_id,file_number,committee_name.1,entity_type,...,filing_form,link_id,is_individual,memo_text,two_year_transaction_period,schedule_type,increased_limit,sub_id,pdf_url,line_number_label
0,C00697441,"PETE FOR AMERICA, INC.",2019,Q2,201907159151242990,17A,1083238,1341083,NaN,IND,...,F3P,4071620191659583353,t,NaN,2020,SA,NaN,4072320191660948261,http://docquery.fec.gov/cgi-bin/fecimg/?201907...,Contributions From Individuals/Persons Other T...
1,C00697441,"PETE FOR AMERICA, INC.",2019,Q2,201907159151242990,17A,1041164,1341083,NaN,IND,...,F3P,4071620191659583353,t,* EARMARKED CONTRIBUTION: SEE BELOW,2020,SA,NaN,4072320191660948262,http://docquery.fec.gov/cgi-bin/fecimg/?201907...,Contributions From Individuals/Persons Other T...
2,C00697441,"PETE FOR AMERICA, INC.",2019,Q2,201907159151242991,17A,761029,1341083,NaN,IND,...,F3P,4071620191659583353,t,* EARMARKED CONTRIBUTION: SEE BELOW,2020,SA,NaN,4072320191660948264,http://docquery.fec.gov/cgi-bin/fecimg/?201907...,Contributions From Individuals/Persons Other T...
3,C00697441,"PETE FOR AMERICA, INC.",2019,Q2,201907159151242992,17A,960782,1341083,NaN,IND,...,F3P,4071620191659583353,t,* EARMARKED CONTRIBUTION: SEE BELOW,2020,SA,NaN,4072320191660948266,http://docquery.fec.gov/cgi-bin/fecimg/?201907...,Contributions From Individuals/Persons Other T...
4,C00697441,"PETE FOR AMERICA, INC.",2019,Q2,201907159151242992,17A,781430,1341083,NaN,IND,...,F3P,4071620191659583353,t,* EARMARKED CONTRIBUTION: SEE BELOW,2020,SA,NaN,4072320191660948268,http://docquery.fec.gov/cgi-bin/fecimg/?201907...,Contributions From Individuals/Persons Other T...

In [8]:
df = df[['committee_name','contributor_zip','contribution_receipt_amount']]

df.head()

           committee_name contributor_zip  contribution_receipt_amount
0  PETE FOR AMERICA, INC.       168016602                        22.27
1  PETE FOR AMERICA, INC.       168016602                         3.00
2  PETE FOR AMERICA, INC.       200091804                       100.00
3  PETE FOR AMERICA, INC.       200091804                       100.00
4  PETE FOR AMERICA, INC.       980335556                        10.00

In [9]:
df = df[['committee_name','contributor_zip','contribution_receipt_amount']]

df['contributor_zip'] = df['contributor_zip'].astype(str)

df['new_zip'] = df['contributor_zip'].str[0:5]

df = df[['committee_name', 'new_zip', 'contribution_receipt_amount']]
df = df.rename(columns = {'new_zip':'zip code'})

In [10]:
df = df.dropna()

df = df[df['zip code'] != '0.0']

df.columns = ['Candidate', 'Zip Code', 'Donation']
df.head()

                Candidate Zip Code  Donation
0  PETE FOR AMERICA, INC.    16801     22.27
1  PETE FOR AMERICA, INC.    16801      3.00
2  PETE FOR AMERICA, INC.    20009    100.00
3  PETE FOR AMERICA, INC.    20009    100.00
4  PETE FOR AMERICA, INC.    98033     10.00

In [ ]:
###Create Database Connection

rds_connection_string = f"postgres:PASSWORD@localhost:5432/campaign_db"

engine = create_engine(f'postgresql://{rds_connection_string}')

# Confirm tables

engine.table_names()

###Load into Database

clean_zip_df.to_sql(name='clean_zip_df', con=engine, if_exists='append', index=False)

pd.read_sql_query('select * from clean_zip_df', con=engine).head()